//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.model.document.page;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for ST_DashCap.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ST_DashCap">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Flat"/>
 *     &lt;enumeration value="Round"/>
 *     &lt;enumeration value="Square"/>
 *     &lt;enumeration value="Triangle"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum STDashCap {

    @XmlEnumValue("Flat")
    FLAT("Flat"),
    @XmlEnumValue("Round")
    ROUND("Round"),
    @XmlEnumValue("Square")
    SQUARE("Square"),
    @XmlEnumValue("Triangle")
    TRIANGLE("Triangle");
    private final String value;

    STDashCap(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static STDashCap fromValue(String v) {
        for (STDashCap c: STDashCap.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
