//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.model.document.page;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for ST_LineJoin.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ST_LineJoin">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Miter"/>
 *     &lt;enumeration value="Bevel"/>
 *     &lt;enumeration value="Round"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum STLineJoin {

    @XmlEnumValue("Miter")
    MITER("Miter"),
    @XmlEnumValue("Bevel")
    BEVEL("Bevel"),
    @XmlEnumValue("Round")
    ROUND("Round");
    private final String value;

    STLineJoin(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static STLineJoin fromValue(String v) {
        for (STLineJoin c: STLineJoin.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
