//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import java.util.ArrayList;
import java.util.List;

import javaaxp.core.service.model.document.page.IBrush;
import javaaxp.core.service.model.document.page.ICanvas;
import javaaxp.core.service.model.document.page.IGeometry;
import javaaxp.core.service.model.document.page.IPageResources;
import javaaxp.core.service.model.document.page.ITransform;
import javaaxp.core.service.model.document.page.STEdgeMode;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CT_Canvas complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_Canvas">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Canvas.Resources" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Canvas.RenderTransform" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Canvas.Clip" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Canvas.OpacityMask" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Path"/>
 *           &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Glyphs"/>
 *           &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Canvas"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/xps/2005/06}AG_Canvas"/>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/xps/2005/06}AG_AutomationProvider"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_Canvas", propOrder = {
    "canvasResources",
    "canvasRenderTransform",
    "canvasClip",
    "canvasOpacityMask",
    "pathOrGlyphsOrCanvas"
})
public class CTCanvas implements ICanvas {

    @XmlElement(name = "Canvas.Resources")
    protected CTCPResources canvasResources;
    @XmlElement(name = "Canvas.RenderTransform")
    protected CTCPTransform canvasRenderTransform;
    @XmlElement(name = "Canvas.Clip")
    protected CTCPGeometry canvasClip;
    @XmlElement(name = "Canvas.OpacityMask")
    protected CTCPBrush canvasOpacityMask;
    @XmlElements({
        @XmlElement(name = "Path", type = CTPath.class),
        @XmlElement(name = "Canvas", type = CTCanvas.class),
        @XmlElement(name = "Glyphs", type = CTGlyphs.class)
    })
    protected List<Object> pathOrGlyphsOrCanvas;
    @XmlAttribute(name = "Clip")
    protected String clip;
    @XmlAttribute(name = "FixedPage.NavigateUri")
    protected String fixedPageNavigateUri;
    @XmlAttribute(name = "Name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String name;
    @XmlAttribute(name = "Opacity")
    protected Double opacity;
    @XmlAttribute(name = "OpacityMask")
    protected String opacityMask;
    @XmlAttribute(name = "RenderOptions.EdgeMode")
    protected STEdgeMode renderOptionsEdgeMode;
    @XmlAttribute(name = "RenderTransform")
    protected String renderTransform;
    @XmlAttribute(name = "Key", namespace = "http://schemas.microsoft.com/xps/2005/06/resourcedictionary-key")
    protected String key;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "AutomationProperties.HelpText")
    protected String automationPropertiesHelpText;
    @XmlAttribute(name = "AutomationProperties.Name")
    protected String automationPropertiesName;

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getCanvasResources()
	 */
    public IPageResources getCanvasResources() {
        return canvasResources;
    }

    /**
     * Sets the value of the canvasResources property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPResources }
     *     
     */
    public void setCanvasResources(CTCPResources value) {
        this.canvasResources = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getCanvasRenderTransform()
	 */
    public ITransform getCanvasRenderTransform() {
        return canvasRenderTransform;
    }

    /**
     * Sets the value of the canvasRenderTransform property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPTransform }
     *     
     */
    public void setCanvasRenderTransform(CTCPTransform value) {
        this.canvasRenderTransform = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getCanvasClip()
	 */
    public IGeometry getCanvasClip() {
        return canvasClip;
    }

    /**
     * Sets the value of the canvasClip property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPGeometry }
     *     
     */
    public void setCanvasClip(CTCPGeometry value) {
        this.canvasClip = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getCanvasOpacityMask()
	 */
    public IBrush getCanvasOpacityMask() {
        return canvasOpacityMask;
    }

    /**
     * Sets the value of the canvasOpacityMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPBrush }
     *     
     */
    public void setCanvasOpacityMask(CTCPBrush value) {
        this.canvasOpacityMask = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getPathOrGlyphsOrCanvas()
	 */
    public List<Object> getPathOrGlyphsOrCanvas() {
        if (pathOrGlyphsOrCanvas == null) {
            pathOrGlyphsOrCanvas = new ArrayList<Object>();
        }
        return this.pathOrGlyphsOrCanvas;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getClip()
	 */
    public String getClip() {
        return clip;
    }

    /**
     * Sets the value of the clip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClip(String value) {
        this.clip = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getFixedPageNavigateUri()
	 */
    public String getFixedPageNavigateUri() {
        return fixedPageNavigateUri;
    }

    /**
     * Sets the value of the fixedPageNavigateUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedPageNavigateUri(String value) {
        this.fixedPageNavigateUri = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getName()
	 */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getOpacity()
	 */
    public double getOpacity() {
        if (opacity == null) {
            return  1.0D;
        } else {
            return opacity;
        }
    }

    /**
     * Sets the value of the opacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOpacity(Double value) {
        this.opacity = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getOpacityMask()
	 */
    public String getOpacityMask() {
        return opacityMask;
    }

    /**
     * Sets the value of the opacityMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpacityMask(String value) {
        this.opacityMask = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getRenderOptionsEdgeMode()
	 */
    public STEdgeMode getRenderOptionsEdgeMode() {
        return renderOptionsEdgeMode;
    }

    /**
     * Sets the value of the renderOptionsEdgeMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link STEdgeMode }
     *     
     */
    public void setRenderOptionsEdgeMode(STEdgeMode value) {
        this.renderOptionsEdgeMode = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getRenderTransform()
	 */
    public String getRenderTransform() {
        return renderTransform;
    }

    /**
     * Sets the value of the renderTransform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenderTransform(String value) {
        this.renderTransform = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getKey()
	 */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getLang()
	 */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getAutomationPropertiesHelpText()
	 */
    public String getAutomationPropertiesHelpText() {
        return automationPropertiesHelpText;
    }

    /**
     * Sets the value of the automationPropertiesHelpText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutomationPropertiesHelpText(String value) {
        this.automationPropertiesHelpText = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ICanvas#getAutomationPropertiesName()
	 */
    public String getAutomationPropertiesName() {
        return automationPropertiesName;
    }

    /**
     * Sets the value of the automationPropertiesName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutomationPropertiesName(String value) {
        this.automationPropertiesName = value;
    }

}
