//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import javaaxp.core.service.model.document.page.ITransform;
import javaaxp.core.service.model.document.page.ITransformMatrix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_CP_Transform complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_CP_Transform">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}MatrixTransform"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_CP_Transform", propOrder = {
    "matrixTransform"
})
public class CTCPTransform implements ITransform {

    @XmlElement(name = "MatrixTransform", required = true)
    protected CTMatrixTransform matrixTransform;

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ITransform#getMatrixTransform()
	 */
    public ITransformMatrix getMatrixTransform() {
        return matrixTransform;
    }

    /**
     * Sets the value of the matrixTransform property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTMatrixTransform }
     *     
     */
    public void setMatrixTransform(CTMatrixTransform value) {
        this.matrixTransform = value;
    }

}
