//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import javaaxp.core.service.model.document.page.ICanvas;
import javaaxp.core.service.model.document.page.IGlyphs;
import javaaxp.core.service.model.document.page.IPath;
import javaaxp.core.service.model.document.page.IVisual;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_CP_Visual complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_CP_Visual">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Path"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Glyphs"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Canvas"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_CP_Visual", propOrder = {
    "path",
    "glyphs",
    "canvas"
})
public class CTCPVisual implements IVisual  {

    @XmlElement(name = "Path")
    protected CTPath path;
    @XmlElement(name = "Glyphs")
    protected CTGlyphs glyphs;
    @XmlElement(name = "Canvas")
    protected CTCanvas canvas;

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IVisual#getPath()
	 */
    public IPath getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTPath }
     *     
     */
    public void setPath(CTPath value) {
        this.path = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IVisual#getGlyphs()
	 */
    public IGlyphs getGlyphs() {
        return glyphs;
    }

    /**
     * Sets the value of the glyphs property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTGlyphs }
     *     
     */
    public void setGlyphs(CTGlyphs value) {
        this.glyphs = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IVisual#getCanvas()
	 */
    public ICanvas getCanvas() {
        return canvas;
    }

    /**
     * Sets the value of the canvas property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCanvas }
     *     
     */
    public void setCanvas(CTCanvas value) {
        this.canvas = value;
    }

}
