//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import javaaxp.core.service.model.document.page.IPageResourceDictionary;
import javaaxp.core.service.model.document.page.IPageResources;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_CP_Resources complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_CP_Resources">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}ResourceDictionary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_CP_Resources", propOrder = {
    "resourceDictionary"
})
public class CTCPResources implements IPageResources {

    @XmlElement(name = "ResourceDictionary")
    protected CTResourceDictionary resourceDictionary;

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPageResources#getResourceDictionary()
	 */
    public IPageResourceDictionary getResourceDictionary() {
        return resourceDictionary;
    }

    /**
     * Sets the value of the resourceDictionary property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTResourceDictionary }
     *     
     */
    public void setResourceDictionary(CTResourceDictionary value) {
        this.resourceDictionary = value;
    }

}
