//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import javaaxp.core.service.model.document.page.IBrush;
import javaaxp.core.service.model.document.page.IImageBrush;
import javaaxp.core.service.model.document.page.ILinearGradientBrush;
import javaaxp.core.service.model.document.page.IRadialGradientBrush;
import javaaxp.core.service.model.document.page.ISolidColorBrush;
import javaaxp.core.service.model.document.page.IVisualBrush;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_CP_Brush complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_CP_Brush">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}ImageBrush"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}LinearGradientBrush"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}RadialGradientBrush"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}SolidColorBrush"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}VisualBrush"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_CP_Brush", propOrder = {
    "imageBrush",
    "linearGradientBrush",
    "radialGradientBrush",
    "solidColorBrush",
    "visualBrush"
})
public class CTCPBrush implements IBrush {

    @XmlElement(name = "ImageBrush")
    protected CTCPImageBrush imageBrush;
    @XmlElement(name = "LinearGradientBrush")
    protected CTLinearGradientBrush linearGradientBrush;
    @XmlElement(name = "RadialGradientBrush")
    protected CTRadialGradientBrush radialGradientBrush;
    @XmlElement(name = "SolidColorBrush")
    protected CTSolidColorBrush solidColorBrush;
    @XmlElement(name = "VisualBrush")
    protected CTVisualBrush visualBrush;

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IBrush#getImageBrush()
	 */
    public IImageBrush getImageBrush() {
        return imageBrush;
    }

    /**
     * Sets the value of the imageBrush property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPImageBrush }
     *     
     */
    public void setImageBrush(CTCPImageBrush value) {
        this.imageBrush = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IBrush#getLinearGradientBrush()
	 */
    public ILinearGradientBrush getLinearGradientBrush() {
        return linearGradientBrush;
    }

    /**
     * Sets the value of the linearGradientBrush property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTLinearGradientBrush }
     *     
     */
    public void setLinearGradientBrush(CTLinearGradientBrush value) {
        this.linearGradientBrush = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IBrush#getRadialGradientBrush()
	 */
    public IRadialGradientBrush getRadialGradientBrush() {
        return radialGradientBrush;
    }

    /**
     * Sets the value of the radialGradientBrush property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTRadialGradientBrush }
     *     
     */
    public void setRadialGradientBrush(CTRadialGradientBrush value) {
        this.radialGradientBrush = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IBrush#getSolidColorBrush()
	 */
    public ISolidColorBrush getSolidColorBrush() {
        return solidColorBrush;
    }

    /**
     * Sets the value of the solidColorBrush property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTSolidColorBrush }
     *     
     */
    public void setSolidColorBrush(CTSolidColorBrush value) {
        this.solidColorBrush = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IBrush#getVisualBrush()
	 */
    public IVisualBrush getVisualBrush() {
        return visualBrush;
    }

    /**
     * Sets the value of the visualBrush property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTVisualBrush }
     *     
     */
    public void setVisualBrush(CTVisualBrush value) {
        this.visualBrush = value;
    }

}
