//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import javaaxp.core.service.model.document.IDocumentOutline;
import javaaxp.core.service.model.document.IOutline;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_CP_Outline complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_CP_Outline">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06/documentstructure}DocumentOutline"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_CP_Outline", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", propOrder = {
    "documentOutline"
})
public class CTCPOutline implements IOutline {

    @XmlElement(name = "DocumentOutline", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", required = true)
    protected CTDocumentOutline documentOutline;

    /* (non-Javadoc)
	 * @see xps.impl.document.jaxb.IDocumentOutline#getDocumentOutline()
	 */
    public IDocumentOutline getDocumentOutline() {
        return documentOutline;
    }

    /**
     * Sets the value of the documentOutline property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTDocumentOutline }
     *     
     */
    public void setDocumentOutline(CTDocumentOutline value) {
        this.documentOutline = value;
    }

}
