//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import java.util.ArrayList;
import java.util.List;

import javaaxp.core.service.model.document.IDocumentStructure;
import javaaxp.core.service.model.document.IOutline;
import javaaxp.core.service.model.document.IStory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_DocumentStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_DocumentStructure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06/documentstructure}DocumentStructure.Outline" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06/documentstructure}Story" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_DocumentStructure", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", propOrder = {
    "documentStructureOutline",
    "story"
})
public class CTDocumentStructure implements IDocumentStructure {

    @XmlElement(name = "DocumentStructure.Outline", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure")
    protected CTCPOutline documentStructureOutline;
    @XmlElement(name = "Story", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure")
    protected List<CTStory> story;

    /* (non-Javadoc)
	 * @see xps.impl.document.jaxb.IDocumentStructure#getDocumentStructureOutline()
	 */
    public IOutline getDocumentStructureOutline() {
        return documentStructureOutline;
    }

    /**
     * Sets the value of the documentStructureOutline property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPOutline }
     *     
     */
    public void setDocumentStructureOutline(CTCPOutline value) {
        this.documentStructureOutline = value;
    }

    /* (non-Javadoc)
	 * @see xps.impl.document.jaxb.IDocumentStructure#getStory()
	 */
    public List<? extends IStory> getStory() {
        if (story == null) {
            story = new ArrayList<CTStory>();
        }
        return this.story;
    }

}
