//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import java.util.ArrayList;
import java.util.List;

import javaaxp.core.service.model.document.IFixedDocumentSequence;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_FixedDocumentSequence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_FixedDocumentSequence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}DocumentReference" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_FixedDocumentSequence", propOrder = {
    "documentReference"
})
public class CTFixedDocumentSequence implements IFixedDocumentSequence {

    @XmlElement(name = "DocumentReference", required = true)
    protected List<CTDocumentReference> documentReference;

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IFixedDocumentSequence#getDocumentReference()
	 */
    /* (non-Javadoc)
	 * @see xps.document.jaxb.IFixedDocumentReference#getDocumentReference()
	 */
    public List<CTDocumentReference> getDocumentReference() {
        if (documentReference == null) {
            documentReference = new ArrayList<CTDocumentReference>();
        }
        return this.documentReference;
    }

}
