//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import javaaxp.core.service.model.document.page.IGlyphs;
import javaaxp.core.service.model.document.page.STStyleSimulations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CT_Glyphs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_Glyphs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Glyphs.RenderTransform" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Glyphs.Clip" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Glyphs.OpacityMask" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Glyphs.Fill" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/xps/2005/06}AG_Glyphs"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_Glyphs", propOrder = {
    "glyphsRenderTransform",
    "glyphsClip",
    "glyphsOpacityMask",
    "glyphsFill"
})
public class CTGlyphs implements IGlyphs {

    @XmlElement(name = "Glyphs.RenderTransform")
    protected CTCPTransform glyphsRenderTransform;
    @XmlElement(name = "Glyphs.Clip")
    protected CTCPGeometry glyphsClip;
    @XmlElement(name = "Glyphs.OpacityMask")
    protected CTCPBrush glyphsOpacityMask;
    @XmlElement(name = "Glyphs.Fill")
    protected CTCPBrush glyphsFill;
    @XmlAttribute(name = "BidiLevel")
    protected Integer bidiLevel;
    @XmlAttribute(name = "CaretStops")
    protected String caretStops;
    @XmlAttribute(name = "Clip")
    protected String clip;
    @XmlAttribute(name = "DeviceFontName")
    protected String deviceFontName;
    @XmlAttribute(name = "Fill")
    protected String fill;
    @XmlAttribute(name = "FixedPage.NavigateUri")
    protected String fixedPageNavigateUri;
    @XmlAttribute(name = "FontRenderingEmSize", required = true)
    protected double fontRenderingEmSize;
    @XmlAttribute(name = "FontUri", required = true)
    protected String fontUri;
    @XmlAttribute(name = "Indices")
    protected String indices;
    @XmlAttribute(name = "IsSideways")
    protected Boolean isSideways;
    @XmlAttribute(name = "Name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String name;
    @XmlAttribute(name = "Opacity")
    protected Double opacity;
    @XmlAttribute(name = "OpacityMask")
    protected String opacityMask;
    @XmlAttribute(name = "OriginX", required = true)
    protected double originX;
    @XmlAttribute(name = "OriginY", required = true)
    protected double originY;
    @XmlAttribute(name = "RenderTransform")
    protected String renderTransform;
    @XmlAttribute(name = "StyleSimulations")
    protected STStyleSimulations styleSimulations;
    @XmlAttribute(name = "UnicodeString")
    protected String unicodeString;
    @XmlAttribute(name = "Key", namespace = "http://schemas.microsoft.com/xps/2005/06/resourcedictionary-key")
    protected String key;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getGlyphsRenderTransform()
	 */
    public CTCPTransform getGlyphsRenderTransform() {
        return glyphsRenderTransform;
    }

    /**
     * Sets the value of the glyphsRenderTransform property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPTransform }
     *     
     */
    public void setGlyphsRenderTransform(CTCPTransform value) {
        this.glyphsRenderTransform = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getGlyphsClip()
	 */
    public CTCPGeometry getGlyphsClip() {
        return glyphsClip;
    }

    /**
     * Sets the value of the glyphsClip property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPGeometry }
     *     
     */
    public void setGlyphsClip(CTCPGeometry value) {
        this.glyphsClip = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getGlyphsOpacityMask()
	 */
    public CTCPBrush getGlyphsOpacityMask() {
        return glyphsOpacityMask;
    }

    /**
     * Sets the value of the glyphsOpacityMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPBrush }
     *     
     */
    public void setGlyphsOpacityMask(CTCPBrush value) {
        this.glyphsOpacityMask = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getGlyphsFill()
	 */
    public CTCPBrush getGlyphsFill() {
        return glyphsFill;
    }

    /**
     * Sets the value of the glyphsFill property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPBrush }
     *     
     */
    public void setGlyphsFill(CTCPBrush value) {
        this.glyphsFill = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getBidiLevel()
	 */
    public int getBidiLevel() {
        if (bidiLevel == null) {
            return  0;
        } else {
            return bidiLevel;
        }
    }

    /**
     * Sets the value of the bidiLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBidiLevel(Integer value) {
        this.bidiLevel = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getCaretStops()
	 */
    public String getCaretStops() {
        return caretStops;
    }

    /**
     * Sets the value of the caretStops property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaretStops(String value) {
        this.caretStops = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getClip()
	 */
    public String getClip() {
        return clip;
    }

    /**
     * Sets the value of the clip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClip(String value) {
        this.clip = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getDeviceFontName()
	 */
    public String getDeviceFontName() {
        return deviceFontName;
    }

    /**
     * Sets the value of the deviceFontName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceFontName(String value) {
        this.deviceFontName = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getFill()
	 */
    public String getFill() {
        return fill;
    }

    /**
     * Sets the value of the fill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFill(String value) {
        this.fill = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getFixedPageNavigateUri()
	 */
    public String getFixedPageNavigateUri() {
        return fixedPageNavigateUri;
    }

    /**
     * Sets the value of the fixedPageNavigateUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedPageNavigateUri(String value) {
        this.fixedPageNavigateUri = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getFontRenderingEmSize()
	 */
    public double getFontRenderingEmSize() {
        return fontRenderingEmSize;
    }

    /**
     * Sets the value of the fontRenderingEmSize property.
     * 
     */
    public void setFontRenderingEmSize(double value) {
        this.fontRenderingEmSize = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getFontUri()
	 */
    public String getFontUri() {
        return fontUri;
    }

    /**
     * Sets the value of the fontUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFontUri(String value) {
        this.fontUri = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getIndices()
	 */
    public String getIndices() {
        return indices;
    }

    /**
     * Sets the value of the indices property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndices(String value) {
        this.indices = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#isIsSideways()
	 */
    public boolean isIsSideways() {
        if (isSideways == null) {
            return false;
        } else {
            return isSideways;
        }
    }

    /**
     * Sets the value of the isSideways property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSideways(Boolean value) {
        this.isSideways = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getName()
	 */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getOpacity()
	 */
    public double getOpacity() {
        if (opacity == null) {
            return  1.0D;
        } else {
            return opacity;
        }
    }

    /**
     * Sets the value of the opacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOpacity(Double value) {
        this.opacity = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getOpacityMask()
	 */
    public String getOpacityMask() {
        return opacityMask;
    }

    /**
     * Sets the value of the opacityMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpacityMask(String value) {
        this.opacityMask = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getOriginX()
	 */
    public double getOriginX() {
        return originX;
    }

    /**
     * Sets the value of the originX property.
     * 
     */
    public void setOriginX(double value) {
        this.originX = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getOriginY()
	 */
    public double getOriginY() {
        return originY;
    }

    /**
     * Sets the value of the originY property.
     * 
     */
    public void setOriginY(double value) {
        this.originY = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getRenderTransform()
	 */
    public String getRenderTransform() {
        return renderTransform;
    }

    /**
     * Sets the value of the renderTransform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenderTransform(String value) {
        this.renderTransform = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getStyleSimulations()
	 */
    public STStyleSimulations getStyleSimulations() {
        if (styleSimulations == null) {
            return STStyleSimulations.NONE;
        } else {
            return styleSimulations;
        }
    }

    /**
     * Sets the value of the styleSimulations property.
     * 
     * @param value
     *     allowed object is
     *     {@link STStyleSimulations }
     *     
     */
    public void setStyleSimulations(STStyleSimulations value) {
        this.styleSimulations = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getUnicodeString()
	 */
    public String getUnicodeString() {
        return unicodeString;
    }

    /**
     * Sets the value of the unicodeString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnicodeString(String value) {
        this.unicodeString = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getKey()
	 */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IGlyphs#getLang()
	 */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
