//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import javaaxp.core.service.model.document.IGradientStops;
import javaaxp.core.service.model.document.page.ILinearGradientBrush;
import javaaxp.core.service.model.document.page.ITransform;
import javaaxp.core.service.model.document.page.STClrIntMode;
import javaaxp.core.service.model.document.page.STMappingMode;
import javaaxp.core.service.model.document.page.STSpreadMethod;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_LinearGradientBrush complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_LinearGradientBrush">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}LinearGradientBrush.Transform" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}LinearGradientBrush.GradientStops"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/xps/2005/06}AG_GradientBrush"/>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/xps/2005/06}AG_Brush"/>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/xps/2005/06}AG_LinearGradientBrush"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_LinearGradientBrush", propOrder = {
    "linearGradientBrushTransform",
    "linearGradientBrushGradientStops"
})
public class CTLinearGradientBrush implements ILinearGradientBrush {

    @XmlElement(name = "LinearGradientBrush.Transform")
    protected CTCPTransform linearGradientBrushTransform;
    @XmlElement(name = "LinearGradientBrush.GradientStops", required = true)
    protected CTCPGradientStops linearGradientBrushGradientStops;
    @XmlAttribute(name = "ColorInterpolationMode")
    protected STClrIntMode colorInterpolationMode;
    @XmlAttribute(name = "MappingMode", required = true)
    protected STMappingMode mappingMode;
    @XmlAttribute(name = "SpreadMethod")
    protected STSpreadMethod spreadMethod;
    @XmlAttribute(name = "Opacity")
    protected Double opacity;
    @XmlAttribute(name = "Key", namespace = "http://schemas.microsoft.com/xps/2005/06/resourcedictionary-key")
    protected String key;
    @XmlAttribute(name = "EndPoint", required = true)
    protected String endPoint;
    @XmlAttribute(name = "StartPoint", required = true)
    protected String startPoint;
    @XmlAttribute(name = "Transform")
    protected String transform;

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ILinearGradientBrush#getLinearGradientBrushTransform()
	 */
    public ITransform getLinearGradientBrushTransform() {
        return linearGradientBrushTransform;
    }

    /**
     * Sets the value of the linearGradientBrushTransform property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPTransform }
     *     
     */
    public void setLinearGradientBrushTransform(CTCPTransform value) {
        this.linearGradientBrushTransform = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ILinearGradientBrush#getLinearGradientBrushGradientStops()
	 */
    public IGradientStops getLinearGradientBrushGradientStops() {
        return linearGradientBrushGradientStops;
    }

    /**
     * Sets the value of the linearGradientBrushGradientStops property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPGradientStops }
     *     
     */
    public void setLinearGradientBrushGradientStops(CTCPGradientStops value) {
        this.linearGradientBrushGradientStops = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ILinearGradientBrush#getColorInterpolationMode()
	 */
    public STClrIntMode getColorInterpolationMode() {
        if (colorInterpolationMode == null) {
            return STClrIntMode.S_RGB_LINEAR_INTERPOLATION;
        } else {
            return colorInterpolationMode;
        }
    }

    /**
     * Sets the value of the colorInterpolationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link STClrIntMode }
     *     
     */
    public void setColorInterpolationMode(STClrIntMode value) {
        this.colorInterpolationMode = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ILinearGradientBrush#getMappingMode()
	 */
    public STMappingMode getMappingMode() {
        if (mappingMode == null) {
            return STMappingMode.ABSOLUTE;
        } else {
            return mappingMode;
        }
    }

    /**
     * Sets the value of the mappingMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link STMappingMode }
     *     
     */
    public void setMappingMode(STMappingMode value) {
        this.mappingMode = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ILinearGradientBrush#getSpreadMethod()
	 */
    public STSpreadMethod getSpreadMethod() {
        if (spreadMethod == null) {
            return STSpreadMethod.PAD;
        } else {
            return spreadMethod;
        }
    }

    /**
     * Sets the value of the spreadMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link STSpreadMethod }
     *     
     */
    public void setSpreadMethod(STSpreadMethod value) {
        this.spreadMethod = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ILinearGradientBrush#getOpacity()
	 */
    public double getOpacity() {
        if (opacity == null) {
            return  1.0D;
        } else {
            return opacity;
        }
    }

    /**
     * Sets the value of the opacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOpacity(Double value) {
        this.opacity = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ILinearGradientBrush#getKey()
	 */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ILinearGradientBrush#getEndPoint()
	 */
    public String getEndPoint() {
        return endPoint;
    }

    /**
     * Sets the value of the endPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndPoint(String value) {
        this.endPoint = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ILinearGradientBrush#getStartPoint()
	 */
    public String getStartPoint() {
        return startPoint;
    }

    /**
     * Sets the value of the startPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartPoint(String value) {
        this.startPoint = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.ILinearGradientBrush#getTransform()
	 */
    public String getTransform() {
        return transform;
    }

    /**
     * Sets the value of the transform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransform(String value) {
        this.transform = value;
    }

}
