//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import java.util.ArrayList;
import java.util.List;

import javaaxp.core.service.model.document.page.ILineSegment;
import javaaxp.core.service.model.document.page.IPathFigure;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_PathFigure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_PathFigure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}PolyLineSegment"/>
 *           &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}PolyBezierSegment"/>
 *           &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}ArcSegment"/>
 *           &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}PolyQuadraticBezierSegment"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/xps/2005/06}AG_PathFigure"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_PathFigure", propOrder = {
    "polyLineSegmentOrPolyBezierSegmentOrArcSegment"
})
public class CTPathFigure implements IPathFigure {

    @XmlElements({
        @XmlElement(name = "ArcSegment", type = CTArcSegment.class),
        @XmlElement(name = "PolyLineSegment", type = CTPolyLineSegment.class),
        @XmlElement(name = "PolyQuadraticBezierSegment", type = CTPolyQuadraticBezierSegment.class),
        @XmlElement(name = "PolyBezierSegment", type = CTPolyBezierSegment.class)
    })
	public List<ILineSegment> polyLineSegmentOrPolyBezierSegmentOrArcSegment;
    @XmlAttribute(name = "IsClosed")
	public Boolean isClosed;
    @XmlAttribute(name = "IsFilled")
	public Boolean isFilled;
    @XmlAttribute(name = "StartPoint", required = true)
	public String startPoint;

    /**
     * Gets the value of the polyLineSegmentOrPolyBezierSegmentOrArcSegment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the polyLineSegmentOrPolyBezierSegmentOrArcSegment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolyLineSegmentOrPolyBezierSegmentOrArcSegment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTArcSegment }
     * {@link CTPolyLineSegment }
     * {@link CTPolyQuadraticBezierSegment }
     * {@link CTPolyBezierSegment }
     * 
     * 
     */
    public List<ILineSegment> getPolyLineSegmentOrPolyBezierSegmentOrArcSegment() {
        if (polyLineSegmentOrPolyBezierSegmentOrArcSegment == null) {
            polyLineSegmentOrPolyBezierSegmentOrArcSegment = new ArrayList<ILineSegment>();
        }
        return this.polyLineSegmentOrPolyBezierSegmentOrArcSegment;
    }

    /**
     * Gets the value of the isClosed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsClosed() {
        if (isClosed == null) {
            return false;
        } else {
            return isClosed;
        }
    }

    /**
     * Sets the value of the isClosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsClosed(Boolean value) {
        this.isClosed = value;
    }

    /**
     * Gets the value of the isFilled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsFilled() {
        if (isFilled == null) {
            return true;
        } else {
            return isFilled;
        }
    }

    /**
     * Sets the value of the isFilled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFilled(Boolean value) {
        this.isFilled = value;
    }

    /**
     * Gets the value of the startPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartPoint() {
        return startPoint;
    }

    /**
     * Sets the value of the startPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartPoint(String value) {
        this.startPoint = value;
    }

}
