//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import javaaxp.core.service.model.document.page.IBrush;
import javaaxp.core.service.model.document.page.IGeometry;
import javaaxp.core.service.model.document.page.IPath;
import javaaxp.core.service.model.document.page.ITransform;
import javaaxp.core.service.model.document.page.STDashCap;
import javaaxp.core.service.model.document.page.STLineCap;
import javaaxp.core.service.model.document.page.STLineJoin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CT_Path complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_Path">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Path.RenderTransform" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Path.Clip" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Path.OpacityMask" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Path.Fill" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Path.Stroke" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06}Path.Data" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/xps/2005/06}AG_Path"/>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/xps/2005/06}AG_AutomationProvider"/>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/xps/2005/06}AG_SnapsToDevicePixels"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_Path", propOrder = {
    "pathRenderTransform",
    "pathClip",
    "pathOpacityMask",
    "pathFill",
    "pathStroke",
    "pathData"
})
public class CTPath implements IPath {

    @XmlElement(name = "Path.RenderTransform")
    protected CTCPTransform pathRenderTransform;
    @XmlElement(name = "Path.Clip")
    protected CTCPGeometry pathClip;
    @XmlElement(name = "Path.OpacityMask")
    protected CTCPBrush pathOpacityMask;
    @XmlElement(name = "Path.Fill")
    protected CTCPBrush pathFill;
    @XmlElement(name = "Path.Stroke")
    protected CTCPBrush pathStroke;
    @XmlElement(name = "Path.Data")
    protected CTCPGeometry pathData;
    @XmlAttribute(name = "Clip")
    protected String clip;
    @XmlAttribute(name = "Data")
    protected String data;
    @XmlAttribute(name = "Fill")
    protected String fill;
    @XmlAttribute(name = "FixedPage.NavigateUri")
    protected String fixedPageNavigateUri;
    @XmlAttribute(name = "Name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String name;
    @XmlAttribute(name = "Opacity")
    protected Double opacity;
    @XmlAttribute(name = "OpacityMask")
    protected String opacityMask;
    @XmlAttribute(name = "RenderTransform")
    protected String renderTransform;
    @XmlAttribute(name = "Stroke")
    protected String stroke;
    @XmlAttribute(name = "StrokeDashArray")
    protected String strokeDashArray;
    @XmlAttribute(name = "StrokeDashCap")
    protected STDashCap strokeDashCap;
    @XmlAttribute(name = "StrokeDashOffset")
    protected Double strokeDashOffset;
    @XmlAttribute(name = "StrokeEndLineCap")
    protected STLineCap strokeEndLineCap;
    @XmlAttribute(name = "StrokeLineJoin")
    protected STLineJoin strokeLineJoin;
    @XmlAttribute(name = "StrokeMiterLimit")
    protected Double strokeMiterLimit;
    @XmlAttribute(name = "StrokeStartLineCap")
    protected STLineCap strokeStartLineCap;
    @XmlAttribute(name = "StrokeThickness")
    protected Double strokeThickness;
    @XmlAttribute(name = "Key", namespace = "http://schemas.microsoft.com/xps/2005/06/resourcedictionary-key")
    protected String key;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(name = "AutomationProperties.HelpText")
    protected String automationPropertiesHelpText;
    @XmlAttribute(name = "AutomationProperties.Name")
    protected String automationPropertiesName;
    @XmlAttribute(name = "SnapsToDevicePixels")
    protected Boolean snapsToDevicePixels;

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getPathRenderTransform()
	 */
    public ITransform getPathRenderTransform() {
        return pathRenderTransform;
    }

    /**
     * Sets the value of the pathRenderTransform property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPTransform }
     *     
     */
    public void setPathRenderTransform(CTCPTransform value) {
        this.pathRenderTransform = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getPathClip()
	 */
    public IGeometry getPathClip() {
        return pathClip;
    }

    /**
     * Sets the value of the pathClip property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPGeometry }
     *     
     */
    public void setPathClip(CTCPGeometry value) {
        this.pathClip = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getPathOpacityMask()
	 */
    public IBrush getPathOpacityMask() {
        return pathOpacityMask;
    }

    /**
     * Sets the value of the pathOpacityMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPBrush }
     *     
     */
    public void setPathOpacityMask(CTCPBrush value) {
        this.pathOpacityMask = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getPathFill()
	 */
    public IBrush getPathFill() {
        return pathFill;
    }

    /**
     * Sets the value of the pathFill property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPBrush }
     *     
     */
    public void setPathFill(CTCPBrush value) {
        this.pathFill = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getPathStroke()
	 */
    public IBrush getPathStroke() {
        return pathStroke;
    }

    /**
     * Sets the value of the pathStroke property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPBrush }
     *     
     */
    public void setPathStroke(CTCPBrush value) {
        this.pathStroke = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getPathData()
	 */
    public IGeometry getPathData() {
        return pathData;
    }

    /**
     * Sets the value of the pathData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTCPGeometry }
     *     
     */
    public void setPathData(CTCPGeometry value) {
        this.pathData = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getClip()
	 */
    public String getClip() {
        return clip;
    }

    /**
     * Sets the value of the clip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClip(String value) {
        this.clip = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getData()
	 */
    public String getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setData(String value) {
        this.data = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getFill()
	 */
    public String getFill() {
        return fill;
    }

    /**
     * Sets the value of the fill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFill(String value) {
        this.fill = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getFixedPageNavigateUri()
	 */
    public String getFixedPageNavigateUri() {
        return fixedPageNavigateUri;
    }

    /**
     * Sets the value of the fixedPageNavigateUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedPageNavigateUri(String value) {
        this.fixedPageNavigateUri = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getName()
	 */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getOpacity()
	 */
    public double getOpacity() {
        if (opacity == null) {
            return  1.0D;
        } else {
            return opacity;
        }
    }

    /**
     * Sets the value of the opacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOpacity(Double value) {
        this.opacity = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getOpacityMask()
	 */
    public String getOpacityMask() {
        return opacityMask;
    }

    /**
     * Sets the value of the opacityMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpacityMask(String value) {
        this.opacityMask = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getRenderTransform()
	 */
    public String getRenderTransform() {
        return renderTransform;
    }

    /**
     * Sets the value of the renderTransform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenderTransform(String value) {
        this.renderTransform = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getStroke()
	 */
    public String getStroke() {
        return stroke;
    }

    /**
     * Sets the value of the stroke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStroke(String value) {
        this.stroke = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getStrokeDashArray()
	 */
    public String getStrokeDashArray() {
        return strokeDashArray;
    }

    /**
     * Sets the value of the strokeDashArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrokeDashArray(String value) {
        this.strokeDashArray = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getStrokeDashCap()
	 */
    public STDashCap getStrokeDashCap() {
        if (strokeDashCap == null) {
            return STDashCap.FLAT;
        } else {
            return strokeDashCap;
        }
    }

    /**
     * Sets the value of the strokeDashCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link STDashCap }
     *     
     */
    public void setStrokeDashCap(STDashCap value) {
        this.strokeDashCap = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getStrokeDashOffset()
	 */
    public double getStrokeDashOffset() {
        if (strokeDashOffset == null) {
            return  0.0D;
        } else {
            return strokeDashOffset;
        }
    }

    /**
     * Sets the value of the strokeDashOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStrokeDashOffset(Double value) {
        this.strokeDashOffset = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getStrokeEndLineCap()
	 */
    public STLineCap getStrokeEndLineCap() {
        if (strokeEndLineCap == null) {
            return STLineCap.FLAT;
        } else {
            return strokeEndLineCap;
        }
    }

    /**
     * Sets the value of the strokeEndLineCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link STLineCap }
     *     
     */
    public void setStrokeEndLineCap(STLineCap value) {
        this.strokeEndLineCap = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getStrokeLineJoin()
	 */
    public STLineJoin getStrokeLineJoin() {
        if (strokeLineJoin == null) {
            return STLineJoin.MITER;
        } else {
            return strokeLineJoin;
        }
    }

    /**
     * Sets the value of the strokeLineJoin property.
     * 
     * @param value
     *     allowed object is
     *     {@link STLineJoin }
     *     
     */
    public void setStrokeLineJoin(STLineJoin value) {
        this.strokeLineJoin = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getStrokeMiterLimit()
	 */
    public double getStrokeMiterLimit() {
        if (strokeMiterLimit == null) {
            return  10.0D;
        } else {
            return strokeMiterLimit;
        }
    }

    /**
     * Sets the value of the strokeMiterLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStrokeMiterLimit(Double value) {
        this.strokeMiterLimit = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getStrokeStartLineCap()
	 */
    public STLineCap getStrokeStartLineCap() {
        if (strokeStartLineCap == null) {
            return STLineCap.FLAT;
        } else {
            return strokeStartLineCap;
        }
    }

    /**
     * Sets the value of the strokeStartLineCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link STLineCap }
     *     
     */
    public void setStrokeStartLineCap(STLineCap value) {
        this.strokeStartLineCap = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getStrokeThickness()
	 */
    public double getStrokeThickness() {
        if (strokeThickness == null) {
            return  1.0D;
        } else {
            return strokeThickness;
        }
    }

    /**
     * Sets the value of the strokeThickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStrokeThickness(Double value) {
        this.strokeThickness = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getKey()
	 */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getLang()
	 */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getAutomationPropertiesHelpText()
	 */
    public String getAutomationPropertiesHelpText() {
        return automationPropertiesHelpText;
    }

    /**
     * Sets the value of the automationPropertiesHelpText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutomationPropertiesHelpText(String value) {
        this.automationPropertiesHelpText = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#getAutomationPropertiesName()
	 */
    public String getAutomationPropertiesName() {
        return automationPropertiesName;
    }

    /**
     * Sets the value of the automationPropertiesName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutomationPropertiesName(String value) {
        this.automationPropertiesName = value;
    }

    /* (non-Javadoc)
	 * @see xps.document.jaxb.IPath#isSnapsToDevicePixels()
	 */
    public Boolean isSnapsToDevicePixels() {
        return snapsToDevicePixels;
    }

    /**
     * Sets the value of the snapsToDevicePixels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSnapsToDevicePixels(Boolean value) {
        this.snapsToDevicePixels = value;
    }

}
