//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_StoryFragments complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_StoryFragments">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06/documentstructure}StoryFragment" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_StoryFragments", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", propOrder = {
    "storyFragment"
})
public class CTStoryFragments {

    @XmlElement(name = "StoryFragment", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", required = true)
    protected List<CTStoryFragment> storyFragment;

    /**
     * Gets the value of the storyFragment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storyFragment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStoryFragment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTStoryFragment }
     * 
     * 
     */
    public List<CTStoryFragment> getStoryFragment() {
        if (storyFragment == null) {
            storyFragment = new ArrayList<CTStoryFragment>();
        }
        return this.storyFragment;
    }

}
