//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_TableCell complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_TableCell">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06/documentstructure}ParagraphStructure"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06/documentstructure}ListStructure"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06/documentstructure}TableStructure"/>
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06/documentstructure}FigureStructure"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://schemas.microsoft.com/xps/2005/06/documentstructure}AG_TableCell"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_TableCell", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", propOrder = {
    "paragraphStructureOrListStructureOrTableStructure"
})
public class CTTableCell {

    @XmlElements({
        @XmlElement(name = "ListStructure", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", type = CTList.class),
        @XmlElement(name = "TableStructure", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", type = CTTable.class),
        @XmlElement(name = "FigureStructure", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", type = CTFigure.class),
        @XmlElement(name = "ParagraphStructure", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", type = CTParagraph.class)
    })
    protected List<Object> paragraphStructureOrListStructureOrTableStructure;
    @XmlAttribute(name = "ColumnSpan")
    protected Integer columnSpan;
    @XmlAttribute(name = "RowSpan")
    protected Integer rowSpan;

    /**
     * Gets the value of the paragraphStructureOrListStructureOrTableStructure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paragraphStructureOrListStructureOrTableStructure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParagraphStructureOrListStructureOrTableStructure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTList }
     * {@link CTTable }
     * {@link CTFigure }
     * {@link CTParagraph }
     * 
     * 
     */
    public List<Object> getParagraphStructureOrListStructureOrTableStructure() {
        if (paragraphStructureOrListStructureOrTableStructure == null) {
            paragraphStructureOrListStructureOrTableStructure = new ArrayList<Object>();
        }
        return this.paragraphStructureOrListStructureOrTableStructure;
    }

    /**
     * Gets the value of the columnSpan property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getColumnSpan() {
        if (columnSpan == null) {
            return  1;
        } else {
            return columnSpan;
        }
    }

    /**
     * Sets the value of the columnSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setColumnSpan(Integer value) {
        this.columnSpan = value;
    }

    /**
     * Gets the value of the rowSpan property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getRowSpan() {
        if (rowSpan == null) {
            return  1;
        } else {
            return rowSpan;
        }
    }

    /**
     * Sets the value of the rowSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRowSpan(Integer value) {
        this.rowSpan = value;
    }

}
