//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CT_Table complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_Table">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://schemas.microsoft.com/xps/2005/06/documentstructure}TableRowGroupStructure"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_Table", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", propOrder = {
    "tableRowGroupStructure"
})
public class CTTable {

    @XmlElement(name = "TableRowGroupStructure", namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure")
    protected List<CTTableRowGroup> tableRowGroupStructure;

    /**
     * Gets the value of the tableRowGroupStructure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tableRowGroupStructure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTableRowGroupStructure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTTableRowGroup }
     * 
     * 
     */
    public List<CTTableRowGroup> getTableRowGroupStructure() {
        if (tableRowGroupStructure == null) {
            tableRowGroupStructure = new ArrayList<CTTableRowGroup>();
        }
        return this.tableRowGroupStructure;
    }

}
