//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.10.23 at 11:22:55 PM EDT 
//


package javaaxp.core.service.impl.document.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xps.document.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DocumentReference_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "DocumentReference");
    private final static QName _PathOpacityMask_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Path.OpacityMask");
    private final static QName _ResourceDictionary_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "ResourceDictionary");
    private final static QName _CanvasClip_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Canvas.Clip");
    private final static QName _FixedPage_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "FixedPage");
    private final static QName _PolyBezierSegment_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "PolyBezierSegment");
    private final static QName _LinkTarget_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "LinkTarget");
    private final static QName _ArcSegment_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "ArcSegment");
    private final static QName _DiscardControl_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/discard-control", "DiscardControl");
    private final static QName _StoryFragments_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "StoryFragments");
    private final static QName _PageContent_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "PageContent");
    private final static QName _SectionStructure_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "SectionStructure");
    private final static QName _TableStructure_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "TableStructure");
    private final static QName _SolidColorBrush_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "SolidColorBrush");
    private final static QName _PathGeometryTransform_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "PathGeometry.Transform");
    private final static QName _PathRenderTransform_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Path.RenderTransform");
    private final static QName _DocumentStructureOutline_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "DocumentStructure.Outline");
    private final static QName _PathGeometry_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "PathGeometry");
    private final static QName _PolyQuadraticBezierSegment_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "PolyQuadraticBezierSegment");
    private final static QName _PathData_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Path.Data");
    private final static QName _StoryFragment_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "StoryFragment");
    private final static QName _VisualBrushTransform_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "VisualBrush.Transform");
    private final static QName _GlyphsRenderTransform_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Glyphs.RenderTransform");
    private final static QName _RadialGradientBrushTransform_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "RadialGradientBrush.Transform");
    private final static QName _PageContentLinkTargets_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "PageContent.LinkTargets");
    private final static QName _LinearGradientBrush_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "LinearGradientBrush");
    private final static QName _StoryBreak_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "StoryBreak");
    private final static QName _ImageBrushTransform_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "ImageBrush.Transform");
    private final static QName _ListItemStructure_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "ListItemStructure");
    private final static QName _TableRowStructure_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "TableRowStructure");
    private final static QName _SignatureDefinitions_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/signature-definitions", "SignatureDefinitions");
    private final static QName _PathFigure_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "PathFigure");
    private final static QName _PathFill_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Path.Fill");
    private final static QName _Discard_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/discard-control", "Discard");
    private final static QName _MatrixTransform_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "MatrixTransform");
    private final static QName _Path_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Path");
    private final static QName _FixedDocumentSequence_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "FixedDocumentSequence");
    private final static QName _ParagraphStructure_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "ParagraphStructure");
    private final static QName _PathStroke_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Path.Stroke");
    private final static QName _VisualBrush_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "VisualBrush");
    private final static QName _ListStructure_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "ListStructure");
    private final static QName _FigureStructure_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "FigureStructure");
    private final static QName _TableRowGroupStructure_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "TableRowGroupStructure");
    private final static QName _Glyphs_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Glyphs");
    private final static QName _CanvasRenderTransform_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Canvas.RenderTransform");
    private final static QName _Story_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "Story");
    private final static QName _PolyLineSegment_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "PolyLineSegment");
    private final static QName _StoryFragmentReference_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "StoryFragmentReference");
    private final static QName _LinearGradientBrushTransform_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "LinearGradientBrush.Transform");
    private final static QName _FixedPageResources_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "FixedPage.Resources");
    private final static QName _GlyphsFill_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Glyphs.Fill");
    private final static QName _LinearGradientBrushGradientStops_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "LinearGradientBrush.GradientStops");
    private final static QName _RadialGradientBrush_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "RadialGradientBrush");
    private final static QName _CanvasResources_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Canvas.Resources");
    private final static QName _ImageBrush_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "ImageBrush");
    private final static QName _PathClip_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Path.Clip");
    private final static QName _GlyphsClip_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Glyphs.Clip");
    private final static QName _TableCellStructure_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "TableCellStructure");
    private final static QName _DocumentOutline_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "DocumentOutline");
    private final static QName _OutlineEntry_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "OutlineEntry");
    private final static QName _DocumentStructure_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "DocumentStructure");
    private final static QName _CanvasOpacityMask_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Canvas.OpacityMask");
    private final static QName _RadialGradientBrushGradientStops_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "RadialGradientBrush.GradientStops");
    private final static QName _Canvas_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Canvas");
    private final static QName _VisualBrushVisual_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "VisualBrush.Visual");
    private final static QName _GradientStop_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "GradientStop");
    private final static QName _NamedElement_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06/documentstructure", "NamedElement");
    private final static QName _GlyphsOpacityMask_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "Glyphs.OpacityMask");
    private final static QName _FixedDocument_QNAME = new QName("http://schemas.microsoft.com/xps/2005/06", "FixedDocument");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xps.document.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CTGlyphs }
     * 
     */
    public CTGlyphs createCTGlyphs() {
        return new CTGlyphs();
    }

    /**
     * Create an instance of {@link CTStory }
     * 
     */
    public CTStory createCTStory() {
        return new CTStory();
    }

    /**
     * Create an instance of {@link CTCanvas }
     * 
     */
    public CTCanvas createCTCanvas() {
        return new CTCanvas();
    }

    /**
     * Create an instance of {@link CTFixedDocument }
     * 
     */
    public CTFixedDocument createCTFixedDocument() {
        return new CTFixedDocument();
    }

    /**
     * Create an instance of {@link CTDiscard }
     * 
     */
    public CTDiscard createCTDiscard() {
        return new CTDiscard();
    }

    /**
     * Create an instance of {@link CTRadialGradientBrush }
     * 
     */
    public CTRadialGradientBrush createCTRadialGradientBrush() {
        return new CTRadialGradientBrush();
    }

    /**
     * Create an instance of {@link CTStoryFragment }
     * 
     */
    public CTStoryFragment createCTStoryFragment() {
        return new CTStoryFragment();
    }

    /**
     * Create an instance of {@link CTDocumentOutline }
     * 
     */
    public CTDocumentOutline createCTDocumentOutline() {
        return new CTDocumentOutline();
    }

    /**
     * Create an instance of {@link CTCPGradientStops }
     * 
     */
    public CTCPGradientStops createCTCPGradientStops() {
        return new CTCPGradientStops();
    }

    /**
     * Create an instance of {@link CTStoryFragments }
     * 
     */
    public CTStoryFragments createCTStoryFragments() {
        return new CTStoryFragments();
    }

    /**
     * Create an instance of {@link CTCPVisual }
     * 
     */
    public CTCPVisual createCTCPVisual() {
        return new CTCPVisual();
    }

    /**
     * Create an instance of {@link CTMatrixTransform }
     * 
     */
    public CTMatrixTransform createCTMatrixTransform() {
        return new CTMatrixTransform();
    }

    /**
     * Create an instance of {@link CTCPOutline }
     * 
     */
    public CTCPOutline createCTCPOutline() {
        return new CTCPOutline();
    }

    /**
     * Create an instance of {@link CTFixedPage }
     * 
     */
    public CTFixedPage createCTFixedPage() {
        return new CTFixedPage();
    }

    /**
     * Create an instance of {@link CTLinearGradientBrush }
     * 
     */
    public CTLinearGradientBrush createCTLinearGradientBrush() {
        return new CTLinearGradientBrush();
    }

    /**
     * Create an instance of {@link CTTableRow }
     * 
     */
    public CTTableRow createCTTableRow() {
        return new CTTableRow();
    }

    /**
     * Create an instance of {@link CTArcSegment }
     * 
     */
    public CTArcSegment createCTArcSegment() {
        return new CTArcSegment();
    }

    /**
     * Create an instance of {@link CTParagraph }
     * 
     */
    public CTParagraph createCTParagraph() {
        return new CTParagraph();
    }

    /**
     * Create an instance of {@link CTResourceDictionary }
     * 
     */
    public CTResourceDictionary createCTResourceDictionary() {
        return new CTResourceDictionary();
    }

    /**
     * Create an instance of {@link CTListItem }
     * 
     */
    public CTListItem createCTListItem() {
        return new CTListItem();
    }

    /**
     * Create an instance of {@link CTSection }
     * 
     */
    public CTSection createCTSection() {
        return new CTSection();
    }

    /**
     * Create an instance of {@link CTDocumentStructure }
     * 
     */
    public CTDocumentStructure createCTDocumentStructure() {
        return new CTDocumentStructure();
    }

    /**
     * Create an instance of {@link CTNamedElement }
     * 
     */
    public CTNamedElement createCTNamedElement() {
        return new CTNamedElement();
    }

    /**
     * Create an instance of {@link CTFixedDocumentSequence }
     * 
     */
    public CTFixedDocumentSequence createCTFixedDocumentSequence() {
        return new CTFixedDocumentSequence();
    }

    /**
     * Create an instance of {@link CTLinkTarget }
     * 
     */
    public CTLinkTarget createCTLinkTarget() {
        return new CTLinkTarget();
    }

    /**
     * Create an instance of {@link CTPolyLineSegment }
     * 
     */
    public CTPolyLineSegment createCTPolyLineSegment() {
        return new CTPolyLineSegment();
    }

    /**
     * Create an instance of {@link CTPolyQuadraticBezierSegment }
     * 
     */
    public CTPolyQuadraticBezierSegment createCTPolyQuadraticBezierSegment() {
        return new CTPolyQuadraticBezierSegment();
    }

    /**
     * Create an instance of {@link CTBreak }
     * 
     */
    public CTBreak createCTBreak() {
        return new CTBreak();
    }

    /**
     * Create an instance of {@link SpotLocationType }
     * 
     */
    public SpotLocationType createSpotLocationType() {
        return new SpotLocationType();
    }

    /**
     * Create an instance of {@link CTOutlineEntry }
     * 
     */
    public CTOutlineEntry createCTOutlineEntry() {
        return new CTOutlineEntry();
    }

    /**
     * Create an instance of {@link CTList }
     * 
     */
    public CTList createCTList() {
        return new CTList();
    }

    /**
     * Create an instance of {@link CTTableCell }
     * 
     */
    public CTTableCell createCTTableCell() {
        return new CTTableCell();
    }

    /**
     * Create an instance of {@link CTCPResources }
     * 
     */
    public CTCPResources createCTCPResources() {
        return new CTCPResources();
    }

    /**
     * Create an instance of {@link CTSolidColorBrush }
     * 
     */
    public CTSolidColorBrush createCTSolidColorBrush() {
        return new CTSolidColorBrush();
    }

    /**
     * Create an instance of {@link CTCPLinkTargets }
     * 
     */
    public CTCPLinkTargets createCTCPLinkTargets() {
        return new CTCPLinkTargets();
    }

    /**
     * Create an instance of {@link CTPath }
     * 
     */
    public CTPath createCTPath() {
        return new CTPath();
    }

    /**
     * Create an instance of {@link CTTable }
     * 
     */
    public CTTable createCTTable() {
        return new CTTable();
    }

    /**
     * Create an instance of {@link CTCPBrush }
     * 
     */
    public CTCPBrush createCTCPBrush() {
        return new CTCPBrush();
    }

    /**
     * Create an instance of {@link CTPathGeometry }
     * 
     */
    public CTPathGeometry createCTPathGeometry() {
        return new CTPathGeometry();
    }

    /**
     * Create an instance of {@link CTTableRowGroup }
     * 
     */
    public CTTableRowGroup createCTTableRowGroup() {
        return new CTTableRowGroup();
    }

    /**
     * Create an instance of {@link SignatureDefinitionType }
     * 
     */
    public SignatureDefinitionType createSignatureDefinitionType() {
        return new SignatureDefinitionType();
    }

    /**
     * Create an instance of {@link CTDocumentReference }
     * 
     */
    public CTDocumentReference createCTDocumentReference() {
        return new CTDocumentReference();
    }

    /**
     * Create an instance of {@link CTCPImageBrush }
     * 
     */
    public CTCPImageBrush createCTImageBrush() {
        return new CTCPImageBrush();
    }

    /**
     * Create an instance of {@link CTCPTransform }
     * 
     */
    public CTCPTransform createCTCPTransform() {
        return new CTCPTransform();
    }

    /**
     * Create an instance of {@link CTStoryFragmentReference }
     * 
     */
    public CTStoryFragmentReference createCTStoryFragmentReference() {
        return new CTStoryFragmentReference();
    }

    /**
     * Create an instance of {@link CTFigure }
     * 
     */
    public CTFigure createCTFigure() {
        return new CTFigure();
    }

    /**
     * Create an instance of {@link CTVisualBrush }
     * 
     */
    public CTVisualBrush createCTVisualBrush() {
        return new CTVisualBrush();
    }

    /**
     * Create an instance of {@link CTDiscardControl }
     * 
     */
    public CTDiscardControl createCTDiscardControl() {
        return new CTDiscardControl();
    }

    /**
     * Create an instance of {@link CTGradientStop }
     * 
     */
    public CTGradientStop createCTGradientStop() {
        return new CTGradientStop();
    }

    /**
     * Create an instance of {@link CTPathFigure }
     * 
     */
    public CTPathFigure createCTPathFigure() {
        return new CTPathFigure();
    }

    /**
     * Create an instance of {@link CTPolyBezierSegment }
     * 
     */
    public CTPolyBezierSegment createCTPolyBezierSegment() {
        return new CTPolyBezierSegment();
    }

    /**
     * Create an instance of {@link CTCPGeometry }
     * 
     */
    public CTCPGeometry createCTCPGeometry() {
        return new CTCPGeometry();
    }

    /**
     * Create an instance of {@link CTPageContent }
     * 
     */
    public CTPageContent createCTPageContent() {
        return new CTPageContent();
    }

    /**
     * Create an instance of {@link SignatureDefinitionsType }
     * 
     */
    public SignatureDefinitionsType createSignatureDefinitionsType() {
        return new SignatureDefinitionsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTDocumentReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "DocumentReference")
    public JAXBElement<CTDocumentReference> createDocumentReference(CTDocumentReference value) {
        return new JAXBElement<CTDocumentReference>(_DocumentReference_QNAME, CTDocumentReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPBrush }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Path.OpacityMask")
    public JAXBElement<CTCPBrush> createPathOpacityMask(CTCPBrush value) {
        return new JAXBElement<CTCPBrush>(_PathOpacityMask_QNAME, CTCPBrush.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTResourceDictionary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "ResourceDictionary")
    public JAXBElement<CTResourceDictionary> createResourceDictionary(CTResourceDictionary value) {
        return new JAXBElement<CTResourceDictionary>(_ResourceDictionary_QNAME, CTResourceDictionary.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPGeometry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Canvas.Clip")
    public JAXBElement<CTCPGeometry> createCanvasClip(CTCPGeometry value) {
        return new JAXBElement<CTCPGeometry>(_CanvasClip_QNAME, CTCPGeometry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTFixedPage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "FixedPage")
    public JAXBElement<CTFixedPage> createFixedPage(CTFixedPage value) {
        return new JAXBElement<CTFixedPage>(_FixedPage_QNAME, CTFixedPage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTPolyBezierSegment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "PolyBezierSegment")
    public JAXBElement<CTPolyBezierSegment> createPolyBezierSegment(CTPolyBezierSegment value) {
        return new JAXBElement<CTPolyBezierSegment>(_PolyBezierSegment_QNAME, CTPolyBezierSegment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTLinkTarget }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "LinkTarget")
    public JAXBElement<CTLinkTarget> createLinkTarget(CTLinkTarget value) {
        return new JAXBElement<CTLinkTarget>(_LinkTarget_QNAME, CTLinkTarget.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTArcSegment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "ArcSegment")
    public JAXBElement<CTArcSegment> createArcSegment(CTArcSegment value) {
        return new JAXBElement<CTArcSegment>(_ArcSegment_QNAME, CTArcSegment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTDiscardControl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/discard-control", name = "DiscardControl")
    public JAXBElement<CTDiscardControl> createDiscardControl(CTDiscardControl value) {
        return new JAXBElement<CTDiscardControl>(_DiscardControl_QNAME, CTDiscardControl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTStoryFragments }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "StoryFragments")
    public JAXBElement<CTStoryFragments> createStoryFragments(CTStoryFragments value) {
        return new JAXBElement<CTStoryFragments>(_StoryFragments_QNAME, CTStoryFragments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTPageContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "PageContent")
    public JAXBElement<CTPageContent> createPageContent(CTPageContent value) {
        return new JAXBElement<CTPageContent>(_PageContent_QNAME, CTPageContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTSection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "SectionStructure")
    public JAXBElement<CTSection> createSectionStructure(CTSection value) {
        return new JAXBElement<CTSection>(_SectionStructure_QNAME, CTSection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTTable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "TableStructure")
    public JAXBElement<CTTable> createTableStructure(CTTable value) {
        return new JAXBElement<CTTable>(_TableStructure_QNAME, CTTable.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTSolidColorBrush }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "SolidColorBrush")
    public JAXBElement<CTSolidColorBrush> createSolidColorBrush(CTSolidColorBrush value) {
        return new JAXBElement<CTSolidColorBrush>(_SolidColorBrush_QNAME, CTSolidColorBrush.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPTransform }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "PathGeometry.Transform")
    public JAXBElement<CTCPTransform> createPathGeometryTransform(CTCPTransform value) {
        return new JAXBElement<CTCPTransform>(_PathGeometryTransform_QNAME, CTCPTransform.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPTransform }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Path.RenderTransform")
    public JAXBElement<CTCPTransform> createPathRenderTransform(CTCPTransform value) {
        return new JAXBElement<CTCPTransform>(_PathRenderTransform_QNAME, CTCPTransform.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPOutline }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "DocumentStructure.Outline")
    public JAXBElement<CTCPOutline> createDocumentStructureOutline(CTCPOutline value) {
        return new JAXBElement<CTCPOutline>(_DocumentStructureOutline_QNAME, CTCPOutline.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTPathGeometry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "PathGeometry")
    public JAXBElement<CTPathGeometry> createPathGeometry(CTPathGeometry value) {
        return new JAXBElement<CTPathGeometry>(_PathGeometry_QNAME, CTPathGeometry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTPolyQuadraticBezierSegment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "PolyQuadraticBezierSegment")
    public JAXBElement<CTPolyQuadraticBezierSegment> createPolyQuadraticBezierSegment(CTPolyQuadraticBezierSegment value) {
        return new JAXBElement<CTPolyQuadraticBezierSegment>(_PolyQuadraticBezierSegment_QNAME, CTPolyQuadraticBezierSegment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPGeometry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Path.Data")
    public JAXBElement<CTCPGeometry> createPathData(CTCPGeometry value) {
        return new JAXBElement<CTCPGeometry>(_PathData_QNAME, CTCPGeometry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTStoryFragment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "StoryFragment")
    public JAXBElement<CTStoryFragment> createStoryFragment(CTStoryFragment value) {
        return new JAXBElement<CTStoryFragment>(_StoryFragment_QNAME, CTStoryFragment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPTransform }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "VisualBrush.Transform")
    public JAXBElement<CTCPTransform> createVisualBrushTransform(CTCPTransform value) {
        return new JAXBElement<CTCPTransform>(_VisualBrushTransform_QNAME, CTCPTransform.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPTransform }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Glyphs.RenderTransform")
    public JAXBElement<CTCPTransform> createGlyphsRenderTransform(CTCPTransform value) {
        return new JAXBElement<CTCPTransform>(_GlyphsRenderTransform_QNAME, CTCPTransform.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPTransform }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "RadialGradientBrush.Transform")
    public JAXBElement<CTCPTransform> createRadialGradientBrushTransform(CTCPTransform value) {
        return new JAXBElement<CTCPTransform>(_RadialGradientBrushTransform_QNAME, CTCPTransform.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPLinkTargets }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "PageContent.LinkTargets")
    public JAXBElement<CTCPLinkTargets> createPageContentLinkTargets(CTCPLinkTargets value) {
        return new JAXBElement<CTCPLinkTargets>(_PageContentLinkTargets_QNAME, CTCPLinkTargets.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTLinearGradientBrush }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "LinearGradientBrush")
    public JAXBElement<CTLinearGradientBrush> createLinearGradientBrush(CTLinearGradientBrush value) {
        return new JAXBElement<CTLinearGradientBrush>(_LinearGradientBrush_QNAME, CTLinearGradientBrush.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTBreak }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "StoryBreak")
    public JAXBElement<CTBreak> createStoryBreak(CTBreak value) {
        return new JAXBElement<CTBreak>(_StoryBreak_QNAME, CTBreak.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPTransform }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "ImageBrush.Transform")
    public JAXBElement<CTCPTransform> createImageBrushTransform(CTCPTransform value) {
        return new JAXBElement<CTCPTransform>(_ImageBrushTransform_QNAME, CTCPTransform.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTListItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "ListItemStructure")
    public JAXBElement<CTListItem> createListItemStructure(CTListItem value) {
        return new JAXBElement<CTListItem>(_ListItemStructure_QNAME, CTListItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTTableRow }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "TableRowStructure")
    public JAXBElement<CTTableRow> createTableRowStructure(CTTableRow value) {
        return new JAXBElement<CTTableRow>(_TableRowStructure_QNAME, CTTableRow.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureDefinitionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/signature-definitions", name = "SignatureDefinitions")
    public JAXBElement<SignatureDefinitionsType> createSignatureDefinitions(SignatureDefinitionsType value) {
        return new JAXBElement<SignatureDefinitionsType>(_SignatureDefinitions_QNAME, SignatureDefinitionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTPathFigure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "PathFigure")
    public JAXBElement<CTPathFigure> createPathFigure(CTPathFigure value) {
        return new JAXBElement<CTPathFigure>(_PathFigure_QNAME, CTPathFigure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPBrush }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Path.Fill")
    public JAXBElement<CTCPBrush> createPathFill(CTCPBrush value) {
        return new JAXBElement<CTCPBrush>(_PathFill_QNAME, CTCPBrush.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTDiscard }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/discard-control", name = "Discard")
    public JAXBElement<CTDiscard> createDiscard(CTDiscard value) {
        return new JAXBElement<CTDiscard>(_Discard_QNAME, CTDiscard.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTMatrixTransform }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "MatrixTransform")
    public JAXBElement<CTMatrixTransform> createMatrixTransform(CTMatrixTransform value) {
        return new JAXBElement<CTMatrixTransform>(_MatrixTransform_QNAME, CTMatrixTransform.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTPath }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Path")
    public JAXBElement<CTPath> createPath(CTPath value) {
        return new JAXBElement<CTPath>(_Path_QNAME, CTPath.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTFixedDocumentSequence }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "FixedDocumentSequence")
    public JAXBElement<CTFixedDocumentSequence> createFixedDocumentSequence(CTFixedDocumentSequence value) {
        return new JAXBElement<CTFixedDocumentSequence>(_FixedDocumentSequence_QNAME, CTFixedDocumentSequence.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTParagraph }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "ParagraphStructure")
    public JAXBElement<CTParagraph> createParagraphStructure(CTParagraph value) {
        return new JAXBElement<CTParagraph>(_ParagraphStructure_QNAME, CTParagraph.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPBrush }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Path.Stroke")
    public JAXBElement<CTCPBrush> createPathStroke(CTCPBrush value) {
        return new JAXBElement<CTCPBrush>(_PathStroke_QNAME, CTCPBrush.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTVisualBrush }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "VisualBrush")
    public JAXBElement<CTVisualBrush> createVisualBrush(CTVisualBrush value) {
        return new JAXBElement<CTVisualBrush>(_VisualBrush_QNAME, CTVisualBrush.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "ListStructure")
    public JAXBElement<CTList> createListStructure(CTList value) {
        return new JAXBElement<CTList>(_ListStructure_QNAME, CTList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTFigure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "FigureStructure")
    public JAXBElement<CTFigure> createFigureStructure(CTFigure value) {
        return new JAXBElement<CTFigure>(_FigureStructure_QNAME, CTFigure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTTableRowGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "TableRowGroupStructure")
    public JAXBElement<CTTableRowGroup> createTableRowGroupStructure(CTTableRowGroup value) {
        return new JAXBElement<CTTableRowGroup>(_TableRowGroupStructure_QNAME, CTTableRowGroup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTGlyphs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Glyphs")
    public JAXBElement<CTGlyphs> createGlyphs(CTGlyphs value) {
        return new JAXBElement<CTGlyphs>(_Glyphs_QNAME, CTGlyphs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPTransform }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Canvas.RenderTransform")
    public JAXBElement<CTCPTransform> createCanvasRenderTransform(CTCPTransform value) {
        return new JAXBElement<CTCPTransform>(_CanvasRenderTransform_QNAME, CTCPTransform.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTStory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "Story")
    public JAXBElement<CTStory> createStory(CTStory value) {
        return new JAXBElement<CTStory>(_Story_QNAME, CTStory.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTPolyLineSegment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "PolyLineSegment")
    public JAXBElement<CTPolyLineSegment> createPolyLineSegment(CTPolyLineSegment value) {
        return new JAXBElement<CTPolyLineSegment>(_PolyLineSegment_QNAME, CTPolyLineSegment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTStoryFragmentReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "StoryFragmentReference")
    public JAXBElement<CTStoryFragmentReference> createStoryFragmentReference(CTStoryFragmentReference value) {
        return new JAXBElement<CTStoryFragmentReference>(_StoryFragmentReference_QNAME, CTStoryFragmentReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPTransform }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "LinearGradientBrush.Transform")
    public JAXBElement<CTCPTransform> createLinearGradientBrushTransform(CTCPTransform value) {
        return new JAXBElement<CTCPTransform>(_LinearGradientBrushTransform_QNAME, CTCPTransform.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPResources }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "FixedPage.Resources")
    public JAXBElement<CTCPResources> createFixedPageResources(CTCPResources value) {
        return new JAXBElement<CTCPResources>(_FixedPageResources_QNAME, CTCPResources.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPBrush }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Glyphs.Fill")
    public JAXBElement<CTCPBrush> createGlyphsFill(CTCPBrush value) {
        return new JAXBElement<CTCPBrush>(_GlyphsFill_QNAME, CTCPBrush.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPGradientStops }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "LinearGradientBrush.GradientStops")
    public JAXBElement<CTCPGradientStops> createLinearGradientBrushGradientStops(CTCPGradientStops value) {
        return new JAXBElement<CTCPGradientStops>(_LinearGradientBrushGradientStops_QNAME, CTCPGradientStops.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTRadialGradientBrush }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "RadialGradientBrush")
    public JAXBElement<CTRadialGradientBrush> createRadialGradientBrush(CTRadialGradientBrush value) {
        return new JAXBElement<CTRadialGradientBrush>(_RadialGradientBrush_QNAME, CTRadialGradientBrush.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPResources }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Canvas.Resources")
    public JAXBElement<CTCPResources> createCanvasResources(CTCPResources value) {
        return new JAXBElement<CTCPResources>(_CanvasResources_QNAME, CTCPResources.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPImageBrush }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "ImageBrush")
    public JAXBElement<CTCPImageBrush> createImageBrush(CTCPImageBrush value) {
        return new JAXBElement<CTCPImageBrush>(_ImageBrush_QNAME, CTCPImageBrush.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPGeometry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Path.Clip")
    public JAXBElement<CTCPGeometry> createPathClip(CTCPGeometry value) {
        return new JAXBElement<CTCPGeometry>(_PathClip_QNAME, CTCPGeometry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPGeometry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Glyphs.Clip")
    public JAXBElement<CTCPGeometry> createGlyphsClip(CTCPGeometry value) {
        return new JAXBElement<CTCPGeometry>(_GlyphsClip_QNAME, CTCPGeometry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTTableCell }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "TableCellStructure")
    public JAXBElement<CTTableCell> createTableCellStructure(CTTableCell value) {
        return new JAXBElement<CTTableCell>(_TableCellStructure_QNAME, CTTableCell.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTDocumentOutline }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "DocumentOutline")
    public JAXBElement<CTDocumentOutline> createDocumentOutline(CTDocumentOutline value) {
        return new JAXBElement<CTDocumentOutline>(_DocumentOutline_QNAME, CTDocumentOutline.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTOutlineEntry }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "OutlineEntry")
    public JAXBElement<CTOutlineEntry> createOutlineEntry(CTOutlineEntry value) {
        return new JAXBElement<CTOutlineEntry>(_OutlineEntry_QNAME, CTOutlineEntry.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTDocumentStructure }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "DocumentStructure")
    public JAXBElement<CTDocumentStructure> createDocumentStructure(CTDocumentStructure value) {
        return new JAXBElement<CTDocumentStructure>(_DocumentStructure_QNAME, CTDocumentStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPBrush }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Canvas.OpacityMask")
    public JAXBElement<CTCPBrush> createCanvasOpacityMask(CTCPBrush value) {
        return new JAXBElement<CTCPBrush>(_CanvasOpacityMask_QNAME, CTCPBrush.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPGradientStops }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "RadialGradientBrush.GradientStops")
    public JAXBElement<CTCPGradientStops> createRadialGradientBrushGradientStops(CTCPGradientStops value) {
        return new JAXBElement<CTCPGradientStops>(_RadialGradientBrushGradientStops_QNAME, CTCPGradientStops.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCanvas }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Canvas")
    public JAXBElement<CTCanvas> createCanvas(CTCanvas value) {
        return new JAXBElement<CTCanvas>(_Canvas_QNAME, CTCanvas.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPVisual }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "VisualBrush.Visual")
    public JAXBElement<CTCPVisual> createVisualBrushVisual(CTCPVisual value) {
        return new JAXBElement<CTCPVisual>(_VisualBrushVisual_QNAME, CTCPVisual.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTGradientStop }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "GradientStop")
    public JAXBElement<CTGradientStop> createGradientStop(CTGradientStop value) {
        return new JAXBElement<CTGradientStop>(_GradientStop_QNAME, CTGradientStop.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTNamedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06/documentstructure", name = "NamedElement")
    public JAXBElement<CTNamedElement> createNamedElement(CTNamedElement value) {
        return new JAXBElement<CTNamedElement>(_NamedElement_QNAME, CTNamedElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTCPBrush }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "Glyphs.OpacityMask")
    public JAXBElement<CTCPBrush> createGlyphsOpacityMask(CTCPBrush value) {
        return new JAXBElement<CTCPBrush>(_GlyphsOpacityMask_QNAME, CTCPBrush.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CTFixedDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.microsoft.com/xps/2005/06", name = "FixedDocument")
    public JAXBElement<CTFixedDocument> createFixedDocument(CTFixedDocument value) {
        return new JAXBElement<CTFixedDocument>(_FixedDocument_QNAME, CTFixedDocument.class, null, value);
    }

}
